'use client'
import Link from 'next/link'
import './globals.css'
import { usePathname } from 'next/navigation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        <div className='header'>
          <div className='flex justify-between p-4'>
            <div>LOGO</div>
            <div className='flex gap-4 z-10'>
              <Link href="/" className={`navTitle ${pathname !== '/produtos' && pathname !== '/contato' ? 'navSelected' : ''}`}>Sobre</Link>
              <Link href="/produtos" className={`navTitle ${pathname === '/produtos' ? 'navSelected' : ''}`}>Produtos</Link>
              <Link href="/contato" className={`navTitle ${pathname === '/contato' ? 'navSelected' : ''}`}>Contato</Link>
            </div>
          </div>
        </div>
        <div className='content'>
          {children}
        </div>

        <div
          className={`circle ${pathname === '/produtos' ? 'c1a' : pathname === '/contato' ? 'c2a' : 'c3a'}`}
          />

      </body>
    </html>
  )
}
