"use client";
import Link from "next/link";
import "./globals.css";
import "./main.css";
import { usePathname } from "next/navigation";
import WhatsAppComponent from "./components/WhatsAppComponent";
import LinkedInComponent from "./components/LinkedInComponent";
import FacebookComponent from "./components/FacebookComponent";
import TwitterComponent from "./components/TwitterComponent";
import logo from "../../public/logo.png";
import logo_footer from "../../public/logo_footer.png";
import phone from "../../public/phone.svg";
import Image from "next/image";
import PhoneIcon from "./components/PhoneIcon";
import { useRef, useState, useEffect } from "react";
import SearchIcon from "./components/SearchIcon";
import DropdownArrowIcon from "./components/DropdownArrowIcon";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  const [search, setSearch] = useState<string>("");
  const [isDropdownOpen, setIsDropdownOpen] = useState<boolean>(false);

  const ref = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState<boolean>(false);
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        setIsVisible(entry.isIntersecting);
      },
      {
        root: null, // Use null para o viewport
        rootMargin: "0px", // Margem adicional em relação ao viewport
        threshold: 0.0001, // Quanto do elemento precisa estar visível para ser considerado visível (50%)
      }
    );

    if (ref.current) {
      observer.observe(ref.current);
    }

    return () => {
      if (ref.current) {
        observer.unobserve(ref.current);
      }
    };
  }, []);
  return (
    <html lang="en">
      <body>
        <WhatsAppComponent />
        {/* Header */}
        <div
          className={`bg-gradient-to-r from-ersPrimaryDark to-ersPrimaryLight fixed w-full h-20 top-0 transition z-50`}
        >
          <div className="flex justify-between py-4 px-12 items-center h-20 z-10">
            <div className="w-[164px]">
              <Image src={logo} alt="Logo" />
            </div>
            <div className="flex items-end border-b border-white">
              <input
                className="w-64 bg-transparent placeholder:text-neutral-300 text-white px-4 focus:outline-none"
                placeholder="Buscar"
              />
              <div className="w-4 pb-5 mr-4 h-4  ">
                <SearchIcon />
              </div>
            </div>
            <div className="flex gap-8 z-10">
              <Link
                href="/"
                className={`text-white hover:text-ersPrimaryDark transition font-bold ${
                  pathname !== "/produtos" && pathname !== "/contato"
                    ? "navSelected"
                    : ""
                }`}
              >
                Home
              </Link>
              <Link
                href="/contato"
                className={`text-white hover:text-ersPrimaryDark transition font-bold ${
                  pathname === "/contato" ? "navSelected" : ""
                }`}
              >
                ERS Print
              </Link>
              <div>
                <div className="flex items-center gap-2 group ">
                  <p
                    className={`cursor-pointer text-white group-hover:text-ersPrimaryDark transition font-bold ${
                      pathname === "/produtos" ? "navSelected" : ""
                    }`}
                    onClick={() => {
                      setIsDropdownOpen((prev) => !prev);
                    }}
                  >
                    Produtos
                  </p>
                  <div
                    className={`${
                      isDropdownOpen ? "-rotate-90" : "rotate-0"
                    } transition w-4 h-4 fill-white group-hover:fill-ersPrimaryDark`}
                  >
                    <DropdownArrowIcon />
                  </div>
                </div>
                <div className="absolute right-0">
                  <div
                    className={`${
                      isDropdownOpen ? "opacity-100" : "opacity-0"
                    } transition`}
                  >
                    <div className="h-4 overflow-hidden mb-[6px]">
                      <div className="w-4 h-4 mt-2 rotate-45 bg-neutral-200 ml-auto mr-16 border-2 border-ersPrimaryDark" />
                    </div>
                    <div className="w-48 mt-[-8px] bg-neutral-200 mr-6 rounded shadow-lg z-10  border-t-2 border-ersPrimaryDark">
                      <div className="w-full h-full hover:bg-neutral-300  cursor-pointer rounded-tl rounded-tr hover:shadow-md">
                        <p className="text-neutral-800 px-4 py-2">Cartazes</p>
                      </div>
                      <div className="w-full h-full hover:bg-neutral-300 z-10 cursor-pointer hover:shadow-md">
                        <p className="text-neutral-800 px-4 py-2 border-t border-neutral-300">
                          Etiquietas
                        </p>
                      </div>
                      <div className="w-full h-full hover:bg-neutral-300 z-10 cursor-pointer hover:shadow-md">
                        <p className="text-neutral-800 px-4 py-2 border-t border-neutral-300">
                          Ribbons
                        </p>
                      </div>
                      <div className="w-full h-full hover:bg-neutral-300 z-10 cursor-pointer rounded-bl rounded-br hover:shadow-md">
                        <p className="text-neutral-800 px-4 py-2 border-t border-neutral-300">
                          Insumos ecommerce
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            className={`w-full bg-gradient-to-t from-transparent to-neutral-900 h-4 transition ${
              isVisible
                ? "-translate-y-1 opacity-0 h-0"
                : "translate-y-0 opacity-50"
            } -z-10`}
          />
        </div>

        <div className="w-1 h-20" ref={ref} />
        <div className="content pb-12">{children}</div>

        <div className="bg-ersPrimaryDark">
          <div className="flex items-center w-full py-8 px-24">
            <div className="flex flex-col items-center"></div>
            <div className="grow flex justify-start">OI</div>
            <div className="grow flex justify-center">OI</div>
            <div className="grow flex justify-end">
              <div>
                <div className="flex gap-2 items-center">
                  <div className="w-6 h-6">
                    <PhoneIcon />
                  </div>
                  <p className="text-white ">(11) 91234-5676</p>
                </div>
                <div className="flex gap-2 items-center mt-2">
                  <div className="w-6 h-6">
                    <PhoneIcon />
                  </div>
                  <p className="text-white ">(11) 91234-5678</p>
                </div>
                <div className="flex gap-2 items-center mt-2">
                  <div className="w-6 h-6">
                    <PhoneIcon />
                  </div>
                  <p className="text-white ">(11) 91234-5678</p>
                </div>
              </div>
            </div>
          </div>
          <div className="flex w-full gap-2 items-center px-8">
            <div className="grow border border-ersPrimaryLight" />
            <LinkedInComponent />
            <FacebookComponent />
            <TwitterComponent />
            <div className="grow border border-ersPrimaryLight" />
          </div>
          <div className="flex w-full flex-col items-center p-8">
            <div className="w-24">
              <Image src={logo_footer} alt="Logo" />
            </div>
            {/* <p className="w-full text-center text-ersPrimaryLight font-thin text-sm">
              Todos os direitos reservados
            </p> */}
          </div>
        </div>
      </body>
    </html>
  );
}
